/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.7/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    //id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
    application
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation("libs.junit.jupiter")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

// application {   
    // Define the main class for the application.
//    mainClass = "code.Exercise1"
//}

//tasks.named<Test>("test") {
//    useJUnitPlatform()
//}

rootProject.name = "exercises"
include("app")

